### PR TITLE
Support Direct Pin matrix for split keyboards.

### PR DESCRIPTION
**Pull request by DivineGod**
* [x] Update config to handle Matrix for split firmware
* [x] Implement direct_pin support in split central run function
* [x] Implement direct_pin support in split peripheral run function
* [x] Add peripheral examples
* [x] Add central examples
* [x] Update split config examples
* [ ] Add non-config example
* [x] Update relevant documentation

### CODE REVIEW

**Comment by DivineGod** [comment]
I've tested the updated examples and confirmed that it does indeed work as expected.

I'm not entirely sure the col2row feature is integrated correctly with all the changes, as the config for direct_pins seem a bit unintuitive to me. But that might just be me missing something.

**Comment by HaoboGu** [comment]
@DivineGod Hey, do you have any plan making this PR merged? Since most parts of the PR has been finished, getting it merged should can be very quick.

**Comment by DivineGod** [comment]
Yes, I do. I will rebase to make sure it'll merge well and look at updating all the relevant places in documentation now.

**Comment by DivineGod** [comment]
I have added documentation about using the config to setup direct pin matrix splits.

I've chosen not to document the rust way since it might be a bit confusing and I haven't tested it fully myself yet

**Comment by HaoboGu** [comment]
I'm merging it. Thanks A LOT!

**Pull request merged**
